const { Module } = require("module");

module.exports.User = require("./user");
module.exports.Product = require("./product");
module.exports.Category = require("./category");
module.exports.Subcategory = require("./subCategory");
module.exports.ProductImage = require("./productImages");
module.exports.NewsLetter = require("./newsLetter");
module.exports.Spam = require("./spam");
module.exports.Faq = require("./faq");
module.exports.Notification = require("./notification");
module.exports.HouseAdvertisement = require("./houseAdvertisement");
module.exports.Adds = require("./adds");
module.exports.FeedBack = require("./feedBack");
module.exports.AddsView = require("./addsViews");
module.exports.Shop=require('./shop')
module.exports.ActivityLog = require("./activityLog");
module.exports.ProductOption = require("./productOption");
module.exports.OptionValue = require("./optionsValue");
module.exports.ProductVariant = require("./productVariant");
