module.exports.User = require("./user");
module.exports.Product = require("./product");
module.exports.Category = require("./category");
module.exports.subCategory = require("./subCategory");
module.exports.ProductImage = require("./productImages");
module.exports.NewsLetter = require("./newsLetter");
module.exports.Spam = require("./spam");
module.exports.Faq = require("./faq");
module.exports.Notification = require("./notification");
module.exports.HouseAdvertisement=require('./houseAdvertisement')
module.exports.Adds=require('./adds')
module.exports.AddsView=require('./addsViews')
